#!/bin/sh
# Copyright (C) 2024 YumesomeZakura <1552037053@qq.com>

cpu_usage=$(top -bn1 | head -n2 | awk -F'[ %]+' 'NR==2{print $2}')
output="CPU: ${cpu_usage}%"

if [ -e "/sys/kernel/debug/qca-nss-drv/stats/cpu_load_ubi" ]; then
    nss_avg_utilization=$(awk 'NR==6 {print $2}' /sys/kernel/debug/qca-nss-drv/stats/cpu_load_ubi)
    if [ -n "$nss_avg_utilization" ]; then
        output="${output} HWE: ${nss_avg_utilization}"
    fi
fi

if [ -r "/sys/kernel/debug/ecm/ecm_db/connection_count_simple" ]; then
    connection_count=$(cat /sys/kernel/debug/ecm/ecm_db/connection_count_simple)
    if [ -n "$connection_count" ]; then
        output="${output} ECM: ${connection_count}"
    fi
fi

echo -n "$output"
